module.exports = grammar({
  name: "coffee",

  extras: $ => [
    /[\s\t]+/,
    $.COMMENT,
  ],

  conflicts: $ => [
    [$.destination, $.basic_type],
    [$.dotted_name, $.fn_params],
  ],

  rules: {
    start: $ => seq(optional($.head_comment), repeat($.statement)),
    head_comment: $ => seq("#", repeat(choice($.OPERATOR, $.WORD)), $.NL),
    statement: $ => choice($.NL, choice($.import, choice($.typealias, choice($.extern, choice($.global, $.function))))),
    typealias: $ => seq("alias", $.WORD, "=", $.type),
    extern: $ => seq("extern", $.type, $.WORD, "(", optional($.fn_params), ")"),
    import: $ => seq("import", $.STRING, "as", $.WORD),
    destination: $ => seq($.dotted_name, repeat(seq("[", $.assignable, "]"))),
    dotted_name: $ => seq($.WORD, repeat(seq(".", $.WORD))),
    boolean: $ => choice("true", "false"),
    addr_destination: $ => seq(repeat("&"), $.destination),
    operator: $ => choice("+", choice("/", choice("==", choice("!=", choice("|", choice("&", choice("<=", choice(">=", choice("<", choice(">", choice("*", choice("-", "%")))))))))))),
    mono_assignable: $ => choice($.fn_call, choice($.boolean, choice("null", choice($.addr_destination, choice($.NUMBER, choice($.CHR, $.STRING)))))),
    assignable: $ => seq(optional($.cast), $.mono_assignable, repeat(seq($.operator, $.mono_assignable))),
    global: $ => seq($.type, $.WORD, "=", $.assignable),
    cast: $ => seq("(", $.type, ")"),
    fn_params: $ => seq(seq($.type, $.WORD), repeat(choice(seq(",", $.type, $.WORD), seq(",", $.WORD)))),
    function: $ => seq($.type, $.WORD, "(", optional($.fn_params), seq(")", $.block)),
    structdef: $ => seq(seq("struct", "{", $.NL), repeat(choice(seq($.type, $.WORD, ",", $.NL), $.NL)), "}"),
    basic_type: $ => seq(choice("void", choice("int", choice("bool", choice("chr", choice("str", choice($.structdef, choice($.dotted_name, "..."))))))), repeat(seq("[", "]")), repeat("*")),
    type: $ => seq($.basic_type, optional($.type_trailer)),
    type_fn_params: $ => seq($.type, repeat(seq(",", $.type))),
    type_trailer: $ => seq("(", optional($.type_fn_params), ")", optional($.type_trailer)),
    if_block: $ => seq("if", $.assignable, $.block, optional($.elif_block), $.NL),
    elif_block: $ => choice(seq("elif", $.assignable, $.block, optional($.elif_block)), $.else_block),
    else_block: $ => seq("else", $.block),
    return: $ => seq("return", optional($.assignable), $.NL),
    declaration: $ => choice(seq($.type, $.WORD, "=", $.assignable), choice(seq($.WORD, ":", "=", $.assignable), seq($.type, $.WORD))),
    assignment: $ => seq($.destination, "=", $.assignable),
    fn_args: $ => choice(seq($.assignable, repeat(seq(",", $.assignable))), seq($.NL, repeat(seq($.assignable, ",", $.NL)))),
    fn_call: $ => seq(seq($.destination, "("), optional($.fn_args), ")"),
    keyword: $ => choice("break", "continue"),
    expression: $ => choice($.if_block, choice($.return, choice($.keyword, choice($.for_loop, choice($.function, choice($.assignment, choice($.fn_call, choice($.declaration, $.NL)))))))),
    expressions: $ => repeat1($.expression),
    block: $ => seq("{", $.NL, optional($.expressions), "}"),
    for_loop: $ => seq("for", optional(choice($.declaration, $.assignment)), ";", optional($.assignable), ";", optional($.assignment), $.block, optional($.else_block)),
    WORD: $ => /[a-zA-Z_][a-zA-Z0-9_]*/,
    NUMBER: $ => /[0-9]+/,
    STRING: $ => /"(\\"|[^"])*"|`(\\`|[^`])*`/,
    CHR: $ => /'(\\\\'|[^\'])'/,
    NL: $ => '\n',
    COMMENT: $ => /--.*/,
    OPERATOR: $ => /[\+\-\*\/%&\|<=>!]+/,
  }
});
