#!/usr/bin/env bash
COFFEE_BIN=${COFEE_BIN:-$HOME/.coffee}

case $1 in
    clean)
        rm -rf *.ll *.s run *.out *.dSYM
        ;;

    test)
        ./run main.bn && mv out run
        find . -name '*.test.bn' -exec sh -c "echo && ./run {} && ./out " \;
        rm -rf ./out
        ;;


    test:watch)
        echo "Watchig for file changes..."
        fswatch --include='.bn$' --exclude='.*' . | xargs -I{} bash -c "clear && $0 test && echo 'Test suite completed'"

        ;;

    install)
        # 1. compile the project
        llc coffee.ll > coffee.s
        gcc coffee.s -o coffee

        # 2. move in $PATH output (see install command)
        mkdir -p "$COFFEE_BIN/bin"
        cp coffee syntax.txt "$COFFEE_BIN/bin"
        echo "'coffee' successfully installed!"
        ;;

    build)
        ./run main.bn
        mv out run
        mv debug.ll coffee.ll
        ;;

    prepare)
        ./run main.bn
        mv debug.ll coffee.ll
        ;;

    update)
        # coffee -in main.bn -out run
        ./run main.bn && mv out run
        ;;
esac
