#!/usr/bin/env bash
COFFEE_EXE="coffee"
COFFEE_ROOT=${COFEE_BIN:-$HOME/.coffee}

case $1 in
    clean)
        rm -rf *.ll *.s run *.out *.dSYM
        ;;

    test)
        set -e
        TEST_EXE="./coffee_test"
        "$COFFEE_EXE" main.bn && mv out "${TEST_EXE}"

        [[ ! -z "$COFFEE_DEBUG" ]] && DEBUGGER="${COFFEE_DEBUG:-valgrind}"

        find . -name '*.test.bn' -exec sh -c "echo && $DEBUGGER ${TEST_EXE} {} && $DEBUGGER ./out " \;
        ./coffee_test main.bn
        rm -rf ./out "${TEST_EXE}"
        ;;


    apple-build)
        "$COFFEE_EXE" main.bn && mv ./out "./coffee_test"
        "./coffee_test" "$2"
        llc debug.ll -o debug.s
        clang -fsanitize=address -g -Wall -Wextra ./debug.s -o debug
        lldb ./debug --one-line "run"
        ;;

    test:watch)
        echo "Watchig for file changes..."
        fswatch --include='.bn$' --exclude='.*' . | xargs -I{} bash -c "clear && $0 test && echo 'Test suite completed'"

        ;;

    install)
        # 1. compile the project
        llc coffee.ll -o coffee.s
        gcc coffee.s -o coffee

        # 2. move in $PATH output (see install command)
        mkdir -p "$COFFEE_ROOT/bin"
        rm -f "$COFFEE_ROOT/bin/coffee"
        cp coffee "$COFFEE_ROOT/bin"
        echo "'coffee' successfully installed!"
        ;;

    build)
        ./run main.bn
        mv out run
        mv debug.ll coffee.ll
        ;;

    release)
        "$COFFEE_EXE" main.bn && rm out
        mv debug.ll coffee.ll
        ;;

    update)
        "$0" test
        "$0" release
        "$0" install
        ;;
esac
