#!/usr/bin/env bash
case $1 in
    clean)
        rm -rf *.ll *.s run *.out *.dSYM
        ;;

    test)
        find . -name '*.test.bn' -exec sh -c "echo && coffee -in {} -out {}.out && ./{}.out " \;
        rm -rf a.out
        ;;

    test:watch)
        echo "Watchig for file changes..."
        fswatch --include='.bn$' --exclude='.*' . | xargs -I{} bash -c "clear && $0 test && echo 'Test suite completed'"

        ;;
    install)
        # 1. compile the project
        $0 build
        # 2. move in $PATH output (see install command)
        echo "feature not implemented yet"
        ;;

    *)
        coffee -in main.bn -out run
        ./run main.bn && mv out run
        ;;
esac
